apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nathan-namespace
  labels:
    app: postgres
type: Opaque
data:
    postgres-root-username: <postgres_user>
    postgres-root-password: <postgres_password>