apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: william-namespace
  labels:
    app: postgres
type: Opaque
data:
    postgres-root-username: YcG9zdGdyZXM=
    postgres-root-password: dGhvcnBlMDE2ODU=