apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  labels:
    app: discordbot
type: Opaque
data:
    bot_token: TVRJME9ERTVOamt6TkRZek5qYzVPREE1TncuR0YyTW14LnFqalpsTFI4UlBEa0xzb2JRaHhKSUtNcy1jbTZXbHBMV3RiaVg4
    postgres_user: cG9zdGdyZXM=
    postgres_password: dGhvcnBlMDE2ODU=
    postgres_host: bG9jYWxob3N0