apiVersion: {{ .Values.apiVersion }}
kind: Secret
metadata:
  name: {{ .Values.appSecretName }}
  labels:
    app: {{ .Values.appName }}
type: Opaque
data:
    bot_token: TVRJME9ERTVOamt6TkRZek5qYzVPREE1TncuR0YyTW14LnFqalpsTFI4UlBEa0xzb2JRaHhKSUtNcy1jbTZXbHBMV3RiaVg4
    postgres_user: {{ .Values.secretPostgresHost }}
    postgres_password: dGhvcnBlMDE2ODU=
    postgres_host: {{ .Values.secretPostgresHost }}
