name: docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
       # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build local container
        run: docker build . --file Dockerfile --tag localbuild/testerimage:latest
      
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/testerimage:latest"
          severity-cutoff: critical

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/centralservice:latest

  deployment:
    needs: docker
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy To Rancher Via Helm!
        uses: 'deler-aziz/helm-deploy-action@v1.0.1'
        with:
          namespace: 'william-namespace'
          release: 'helmwtbot'
          chart: './deployments/helmdiscbot'
          token: '${{ github.token }}'
          value-files: './deployments/helmdiscbot/values.yaml'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
        
          
