name: docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build local container
        uses: docker/build-push-action@v6
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true


      - name: Validating K8S Bot Deployment Yaml
        uses: azure/k8s-lint@v1
        with:
          manifests: | 
            'deployments/helmdiscbot/templates/helmDiscBot-configmap.yml'
            'deployments/helmdiscbot/templates/helmDiscBot-deployment.yml'
            'deployments/helmdiscbot/templates/helmDiscBot-secret.yml'
          kubeconformOpts: -summary
          
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/centralservice:latest

  deployment:
    needs: docker
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy To Rancher Via Helm!
        uses: 'deler-aziz/helm-deploy-action@v1.0.1'
        with:
          namespace: 'william-namespace'
          release: 'helmwtbot'
          chart: './deployments/helmdiscbot'
          token: '${{ github.token }}'
          value-files: './deployments/helmdiscbot/values.yaml'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
        
          
