name: docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build local container
        uses: docker/build-push-action@v6
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"

      - name: Validating K8S Bot Deployment Yaml
        uses: makocchi-git/actions-k8s-manifests-validate-conftest@1.1.0
        with:
          files: ./deployments/bot-deployment/bot-deployment.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validating K8S Pgadmin Deployment
        uses: makocchi-git/actions-k8s-manifests-validate-conftest@1.1.0
        with:
          files: ./deployments/pgadmin-deployment/pgadmin-deployment.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validating K8S Postgres Deployment
        uses: makocchi-git/actions-k8s-manifests-validate-conftest@1.1.0
        with:
          files: ./deployments/postgres-deployment/postgres-deployment.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/centralservice:latest

  deployment:
    needs: docker
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy To Rancher Via Helm!
        uses: 'deler-aziz/helm-deploy-action@v1.0.1'
        with:
          namespace: 'william-namespace'
          release: 'helmwtbot'
          chart: './deployments/helmdiscbot'
          token: '${{ github.token }}'
          value-files: './deployments/helmdiscbot/values.yaml'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
        
          
